name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: npm install

      - name: ESLint check
        run: npx eslint --ignore-path .gitignore .

      - name: Test & coverage
        run: npm run test

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v2